version: '3'

services:
  traefik-gateway:
    image: traefik:v2.4
    ports:
      - "80:80"
      - "8090:8080"
      - "443:443"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/etc/traefik
      - ./log:/var/log/traefik
    labels:
      - traefik.http.routers.traefik-gateway.rule=Host(`traefik.mglee.dev`)
      - traefik.http.routers.traefik-gateway.tls.certResolver=gateResolver
      - traefik.http.services.traefik-gateway.loadbalancer.server.port=8080
