version: '3'

services:
  traefik-gateway:
    image: traefik:v2.4
    ports:
      - "80:80"
      - "8090:8080"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - "./:/etc/traefik"
    labels:
      - traefik.http.routers.traefik-gateway.rule=Host(`traefik.mglee.dev`)