api:
  dashboard: true
  insecure: true
  debug: true

entryPoints:
  http:
    address: ":80"
#    http:
#      redirections:
#        entryPoint:
#          to: https
  https:
    address: ":443"

#****************https://doc.traefik.io/traefik/user-guides/docker-compose/acme-dns/ **********************
#
#   Error - 203.254.143.236:80 접근 불가능 - smartXfilter.
#
certificatesResolvers:
  gateResolver:
    acme:
      email: lee95292@naver.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: http


accesslog:
  filePath: /var/log/traefik/accesslog.log
log:
  level: INFO
  filePath: /var/log/traefik/systemlog.log 
  
providers:
  file:
    filename: /etc/traefik/dynamic_conf.yaml
    watch: true
  docker: 
    network: traefik_default